import { Theme } from '@/types/presentation';

export const defaultThemes: Theme[] = [
  {
    id: 'simple-light',
    name: 'Simple Light',
    colors: {
      primary: '#4285F4',
      secondary: '#5F6368',
      accent1: '#4285F4',
      accent2: '#EA4335',
      accent3: '#FBBC04',
      accent4: '#34A853',
      dark1: '#202124',
      dark2: '#3C4043',
      light1: '#FFFFFF',
      light2: '#F1F3F4',
    },
    fontHeading: 'Arial',
    fontBody: 'Arial',
    backgroundDefault: { type: 'solid', color: '#FFFFFF' },
  },
  {
    id: 'simple-dark',
    name: 'Simple Dark',
    colors: {
      primary: '#8AB4F8',
      secondary: '#BDC1C6',
      accent1: '#8AB4F8',
      accent2: '#F28B82',
      accent3: '#FDD663',
      accent4: '#81C995',
      dark1: '#E8EAED',
      dark2: '#BDC1C6',
      light1: '#202124',
      light2: '#303134',
    },
    fontHeading: 'Arial',
    fontBody: 'Arial',
    backgroundDefault: { type: 'solid', color: '#202124' },
  },
  {
    id: 'streamline',
    name: 'Streamline',
    colors: {
      primary: '#1A73E8',
      secondary: '#5F6368',
      accent1: '#1A73E8',
      accent2: '#D93025',
      accent3: '#F9AB00',
      accent4: '#1E8E3E',
      dark1: '#202124',
      dark2: '#3C4043',
      light1: '#FFFFFF',
      light2: '#E8F0FE',
    },
    fontHeading: 'Roboto',
    fontBody: 'Roboto',
    backgroundDefault: { type: 'solid', color: '#FFFFFF' },
  },
  {
    id: 'coral',
    name: 'Coral',
    colors: {
      primary: '#FF6D6D',
      secondary: '#7C7C7C',
      accent1: '#FF6D6D',
      accent2: '#FFB74D',
      accent3: '#FFD54F',
      accent4: '#81C784',
      dark1: '#37474F',
      dark2: '#546E7A',
      light1: '#FFF5F5',
      light2: '#FFEBEE',
    },
    fontHeading: 'Georgia',
    fontBody: 'Arial',
    backgroundDefault: { type: 'solid', color: '#FFF5F5' },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    colors: {
      primary: '#333333',
      secondary: '#999999',
      accent1: '#333333',
      accent2: '#666666',
      accent3: '#999999',
      accent4: '#CCCCCC',
      dark1: '#111111',
      dark2: '#333333',
      light1: '#FFFFFF',
      light2: '#FAFAFA',
    },
    fontHeading: 'Georgia',
    fontBody: 'Arial',
    backgroundDefault: { type: 'solid', color: '#FFFFFF' },
  },
];

export const themes = defaultThemes;

export const getDefaultTheme = (): Theme => defaultThemes[0];
